### ISSUE TITLE
Failed to validate connection issue using MySQL

### ISSUE THREAD

**Issue by jippi** [ChestShop-authors/ChestShopNotifier#52]
Hi,

Firstly, thanks for a great plugin - it's very loved on my server by everyone.

I'm using `mariadb:10.4` (docker image) as MySQL server with no configuration changes done to the server. (All defaults)

We're consistently seeing this error showing up in our logs 

```
[Mon, 30. Aug 2021 17:34:34 CEST INFO] VikingPetz bought 64 Leather for 250.00 from jippignu at [world] -351, 55, 216
[Mon, 30. Aug 2021 17:34:34 CEST WARN] HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@2d6c2057 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[Mon, 30. Aug 2021 17:34:34 CEST WARN] HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@6296c1b1 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[Mon, 30. Aug 2021 17:34:34 CEST WARN] HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@2e343b2c (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[Mon, 30. Aug 2021 17:34:34 CEST WARN] HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@53be42fb (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[Mon, 30. Aug 2021 17:34:34 CEST WARN] HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@56f6e6d8 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[Mon, 30. Aug 2021 17:34:34 CEST WARN] HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@2cd3ba14 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[Mon, 30. Aug 2021 17:34:34 CEST WARN] HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@4df24970 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[Mon, 30. Aug 2021 17:34:34 CEST WARN] HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@6f7c0fe (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[Mon, 30. Aug 2021 17:34:34 CEST WARN] HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@573b3596 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[Mon, 30. Aug 2021 17:34:34 CEST WARN] HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@6609267f (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[Mon, 30. Aug 2021 17:35:51 CEST INFO] VikingPetz bought 64 Melon Slice for 150.00 from jippignu at [world] -351, 55, 212
```

our config file looks like this

```yaml
# Chest Shop Notifier
# Config file for 1.3.3

logging:
  admin-shop: true

notifications:
  notify-on-user-join: true
  delay-seconds: 5

history:
  max-rows: 10
  query-limit: 10000

debugging:
  verbose: false

database:
  # Possible types: SQLite and MySQL
  type: mysql
  dbname: 'minecraft'
  # MySQL specific settings
  host: 'database'
  port: 3306
  username: 'minecraft'
  password: 'xxxxxx'
  ssl: false
```
